# Generated by Django 5.1.1 on 2025-01-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='1', max_length=3, verbose_name='Иконка'),
            preserve_default=False,
        ),
    ]
